// Auto-generated by scripts/build-blog-data.mjs — re-run after updating
// docs/research/blog/posts/*.json or rerunning the asset download script.
// Summary-only data — bodyHtml is fetched per-post from /blog/<slug>.json.
// Source: https://jermayads.nl/blog

export interface BlogPost {
  slug: string;
  title: string;
  /** ISO YYYY-MM-DD */
  date: string;
  excerpt: string;
  /** Local path under public/, or null if no hero. */
  heroImage: string | null;
  /** Original post URL on jermayads.nl — kept for reference only. */
  url: string;
}

export const BLOG_POSTS: BlogPost[] = [
  {
    "slug": "sturen-op-profit-binnen-google-ads",
    "title": "Sturen op profit binnen Google Ads",
    "date": "2024-05-21",
    "excerpt": "Het idee achter Google Ads is eenvoudig: je investeert om een verkoop of ander type conversie te realiseren.",
    "heroImage": "/images/blog/2c092b6db65e3a.jpg",
    "url": "https://jermayads.nl/blog/sturen-op-profit-binnen-google-ads"
  },
  {
    "slug": "de-time-trigger-in-ga4-om-qualityvisits-te-meten",
    "title": "De time trigger in GA4 om QualityVisits te meten",
    "date": "2024-03-29",
    "excerpt": "Het meten van QualityVisits helpt marketeers de kwaliteit van bezoekers in te schatten, vooral in B2B waar conversiedata beperkt is en algoritmen moeite hebben effectief te sturen.",
    "heroImage": "/images/blog/89e6f8688834a3.jpg",
    "url": "https://jermayads.nl/blog/de-time-trigger-in-ga4-om-qualityvisits-te-meten"
  },
  {
    "slug": "assistance-api-wat-is-het-precies",
    "title": "Assistance API: Wat is het precies?",
    "date": "2024-02-27",
    "excerpt": "De OpenAI Assistants API is een tool waarmee je AI-assistants kan maken die je in je eigen applicatie kunt integreren.",
    "heroImage": "/images/blog/3268cf2f35047a.png",
    "url": "https://jermayads.nl/blog/assistance-api-wat-is-het-precies"
  },
  {
    "slug": "conversies-vs-conversies-bij-tijd",
    "title": "Conversies vs. Conversies bij tijd",
    "date": "2024-02-20",
    "excerpt": "Het bijhouden van conversies in Google Ads is historisch gezien onduidelijk geweest. Een nieuw inzicht helpt adverteerders beter te begrijpen wanneer conversies plaatsvinden na een klik.",
    "heroImage": "/images/blog/306381cf254e8d.png",
    "url": "https://jermayads.nl/blog/conversies-vs-conversies-bij-tijd"
  },
  {
    "slug": "tracking-en-consent-mode",
    "title": "Tracking en consent mode",
    "date": "2024-01-28",
    "excerpt": "H2 2024 is het moment dat Google Chrome begint met de uitfasering van 3rd party cookies naar aanleiding van de DMA die in maart 2024 van kracht wordt.",
    "heroImage": "/images/blog/1c8e04a04b8e9d.png",
    "url": "https://jermayads.nl/blog/tracking-en-consent-mode"
  },
  {
    "slug": "videos-automatiseren-met-moviepy",
    "title": "Videos automatiseren met MoviePy",
    "date": "2024-01-20",
    "excerpt": "In 2024 wordt video nog belangrijker, zeker als SGE ook in Nederland komt. Google neigt steeds meer naar content met video en afbeelding in plaats van alleen tekst.",
    "heroImage": "/images/blog/c8ed7bdcd2396c.png",
    "url": "https://jermayads.nl/blog/videos-automatiseren-met-moviepy"
  },
  {
    "slug": "automatiseren-van-prijsextensies-in-google-ads-met-chatgpt4",
    "title": "Automatiseren van prijsextensies in Google Ads met ChatGPT4",
    "date": "2023-12-22",
    "excerpt": "Een script automatiseert prijsuitbreidingen in Google Ads door productfeed-gegevens te koppelen en ChatGPT4 in te zetten voor het herschrijven van titels.",
    "heroImage": "/images/blog/e73c68975dae9a.png",
    "url": "https://jermayads.nl/blog/automatiseren-van-prijsextensies-in-google-ads-met-chatgpt4"
  },
  {
    "slug": "shoppingscraper-dynamic-price-scraper",
    "title": "Shoppingscraper Dynamic Price scraper",
    "date": "2023-12-17",
    "excerpt": "ShoppingScraper is een krachtige scraper om prijsinformatie te verzamelen van producten en leveranciers door EAN-codes of zoekwoorden in te voeren.",
    "heroImage": "/images/blog/7439fadc5f260a.png",
    "url": "https://jermayads.nl/blog/shoppingscraper-dynamic-price-scraper"
  },
  {
    "slug": "automatiseren-van-prijsextensies-in-google-ads",
    "title": "Automatiseren van prijsextensies in Google Ads",
    "date": "2023-12-08",
    "excerpt": "De Google Ads prijsextensie helpt adverteerders door prijzen in advertenties aan te geven. Dit verhoogt meestal de doorklikratio, maar de extensie bevat vaak onnauwkeurige informatie.",
    "heroImage": "/images/blog/c8cd8adaa49f91.png",
    "url": "https://jermayads.nl/blog/automatiseren-van-prijsextensies-in-google-ads"
  },
  {
    "slug": "laadtijd-bijhouden-in-ga4",
    "title": "Laadtijd bijhouden in GA4",
    "date": "2023-11-30",
    "excerpt": "Wil je de laadtijd van pagina's bijhouden in GA4? Momenteel is er geen rapport waarin je de snelheid van de landingspagina's kan meten in GA4.",
    "heroImage": "/images/blog/437419ed7a4509.png",
    "url": "https://jermayads.nl/blog/laadtijd-bijhouden-in-ga4"
  },
  {
    "slug": "neemt-jouw-organisch-verkeer-af",
    "title": "Neemt jouw organisch verkeer af?",
    "date": "2023-11-25",
    "excerpt": "In de afgelopen jaren hebben advertenties, SERP-functies en featured snippets veel clicks uit organische resultaten weggesprokkeld, maar Google maakt het niet makkelijk om deze veranderingen te begrijpen.",
    "heroImage": "/images/blog/9e1c2139e6e624.png",
    "url": "https://jermayads.nl/blog/neemt-jouw-organisch-verkeer-af"
  },
  {
    "slug": "product-ids-analyse-google-shopping-en-performance-max",
    "title": "Product ID's analyse Google Shopping en Performance Max",
    "date": "2023-11-22",
    "excerpt": "Dit script verzamelt diverse data voor items in shopping- of PMax-campagnes, waaronder ROAS, spend, conversiepercentage en meer.",
    "heroImage": "/images/blog/76db366393228f.png",
    "url": "https://jermayads.nl/blog/product-ids-analyse-google-shopping-en-performance-max"
  },
  {
    "slug": "broad-match-is-ai-de-toekomst-betreft-match-types",
    "title": "Broad-match. Is AI de toekomst betreft match types?",
    "date": "2023-11-15",
    "excerpt": "Is brede zoekwoorden de toekomst? Dat is een vraag van veel SEA-specialisten. Nu heb je nog de keuze uit exact-match, phrase-match en broad-match.",
    "heroImage": "/images/blog/37f4e61ea8f733.png",
    "url": "https://jermayads.nl/blog/broad-match-is-ai-de-toekomst-betreft-match-types"
  },
  {
    "slug": "het-minimum-clicks-concept-in-google-ads",
    "title": "Het minimum clicks concept in Google Ads",
    "date": "2023-11-10",
    "excerpt": "Als beginnende PPC specialist zou het concept van minimum clicks de eerste les moeten zijn. Dit gaat erom hoeveel clicks je op zijn minst nodig hebt voor een conversie.",
    "heroImage": "/images/blog/3ea50fb58b0da7.png",
    "url": "https://jermayads.nl/blog/het-minimum-clicks-concept-in-google-ads"
  },
  {
    "slug": "paid-organic-rapportage",
    "title": "Paid Organic rapportage",
    "date": "2023-11-05",
    "excerpt": "Met de rapportage van Paid en Organic kunnen gebruikers hun zoekwoorden analyseren en verbeteren, omdat zowel betaalde als organische zoekopdrachten in één rapport worden gepresenteerd.",
    "heroImage": "/images/blog/a479d3f5b880ec.png",
    "url": "https://jermayads.nl/blog/paid-organic-rapportage"
  },
  {
    "slug": "rag-llm-content-automatiseren-met-behulp-van-rag-zonder-hallucinaties-van-een-llm",
    "title": "RAG LLM: content automatiseren met behulp van RAG zonder hallucinaties van een LLM",
    "date": "2023-10-29",
    "excerpt": "Python kan gebruikt worden voor LLM Automation met RAG (Retrieval Augmented Generation) om bestaande data als betrouwbare bronnen in te zetten voor nauwkeurigere informatie.",
    "heroImage": "/images/blog/714596f838a7a5.png",
    "url": "https://jermayads.nl/blog/rag-llm-content-automatiseren-met-behulp-van-rag-zonder-hallucinaties-van-een-llm"
  },
  {
    "slug": "gebruik-micro-conversies-voor-datagedreven-beslissingen",
    "title": "Gebruik micro-conversies voor datagedreven beslissingen",
    "date": "2023-10-22",
    "excerpt": "Een klant zocht naar meer leads voor constructieberekeningen. Met slechts 2 offerteaanvragen in de eerste maand was er onvoldoende data om op te sturen.",
    "heroImage": "/images/blog/509c425ffabb37.png",
    "url": "https://jermayads.nl/blog/gebruik-micro-conversies-voor-datagedreven-beslissingen"
  },
  {
    "slug": "interne-linkstructuur-automatiseren-met-python",
    "title": "Interne linkstructuur automatiseren met Python",
    "date": "2023-10-14",
    "excerpt": "De interne linkstructuur is cruciaal voor SEO. Een goede structuur helpt zoekmachines beter te begrijpen waar pagina's over gaan en zorgt voor snellere indexering.",
    "heroImage": "/images/blog/c36f23021d9ab9.png",
    "url": "https://jermayads.nl/blog/interne-linkstructuur-automatiseren-met-python"
  },
  {
    "slug": "dynamisch-data-opslaan-in-een-google-spreadsheet-met-de-image-tag",
    "title": "Dynamisch data opslaan in een Google spreadsheet met de Image tag",
    "date": "2023-10-10",
    "excerpt": "Verzend dynamische data naar een Google-spreadsheet met Google Tag Manager voor het opslaan van formulierinzendingen, GCLID en e-mailadressen.",
    "heroImage": "/images/blog/1b6c51e8f3e259.png",
    "url": "https://jermayads.nl/blog/dynamisch-data-opslaan-in-een-google-spreadsheet-met-de-image-tag"
  },
  {
    "slug": "performance-max-hoe-stel-je-die-zo-goed-mogelijk-in",
    "title": "Performance Max: hoe stel je die zo goed mogelijk in",
    "date": "2023-09-30",
    "excerpt": "Performance Max functioneert als een black box zonder heilige graal. De keuze tussen Performance Max en reguliere shopping-campagnes hangt af van specifieke situaties en vereisten.",
    "heroImage": "/images/blog/07e7000f05dc11.png",
    "url": "https://jermayads.nl/blog/performance-max-hoe-stel-je-die-zo-goed-mogelijk-in"
  },
  {
    "slug": "youtube-video-campagnes-handleiding",
    "title": "YouTube video campagnes: handleiding",
    "date": "2023-09-19",
    "excerpt": "YouTube blijft domineren en consumenten zoeken relevante videocontent. Dit artikel biedt praktische adviezen voor het uitvoeren van YouTube-campagnes.",
    "heroImage": "/images/blog/708bc7dbbf818d.png",
    "url": "https://jermayads.nl/blog/youtube-video-campagnes-handleiding"
  },
  {
    "slug": "campagne-creatie-door-scrapen-van-paginas",
    "title": "Campagne creatie door scrapen van pagina's",
    "date": "2023-09-15",
    "excerpt": "In veel accounts zijn de resultaten van DSA-campagnes wisselend. Alternatieve strategieën worden getest door productpagina's uit te scrapen voor betere prestaties.",
    "heroImage": "/images/blog/d7b8752234a01f.png",
    "url": "https://jermayads.nl/blog/campagne-creatie-door-scrapen-van-paginas"
  }
];
